# Generated by Django 5.0.6 on 2024-07-18 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Home_page',
        ),
    ]
